#server.port=8088

server:
  port: 8088

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://49.232.145.111:8096/mydb?serverZoneTime=UTC&&characterEncoding=utf-8
#spring.datasource.username=root
#spring.datasource.password=123456


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.232.145.111:8096/mydb?serverZoneTime=UTC&&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
